app = "mikebeach-ssh-cv"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "2222"

[[services]]
  internal_port = 2222
  protocol = "tcp"

  [[services.ports]]
    port = 22

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "5s"
